package com.reactnativefacetec.Processors;


import android.content.Context;

import com.facetec.sdk.FaceTecCustomization;
import com.facetec.sdk.FaceTecSDK;

public class Config {

  // -------------------------------------
  // REQUIRED
  // Available at https://dev.facetec.com/#/account
  // NOTE: This field is auto-populated by the FaceTec SDK Configuration Wizard.
  public static String DeviceKeyIdentifier = "dbAJm57lOvJ0ViuYtpWOIsUhsGxMTv3c";

  // -------------------------------------
  // REQUIRED
  // The URL to call to process FaceTec SDK Sessions.
  // In Production, you likely will handle network requests elsewhere and without the use of this variable.
  // See https://dev.facetec.com/#/security-best-practices?link=facetec-server-rest-endpoint-security for more information.
  // NOTE: This field is auto-populated by the FaceTec SDK Configuration Wizard.

  //  public static String BaseURL = "https://api.facetec.com/api/v3.1/biometrics"; // Facetec Test Server
  public static String BaseURL = "https://scan.numio.one"; // Numio Server

  // -------------------------------------
  // REQUIRED
  // The FaceScan Encryption Key you define for your application.
  // Please see https://dev.facetec.com/#/licensing-and-encryption-keys for more information.
  // NOTE: This field is auto-populated by the FaceTec SDK Configuration Wizard.
  public static String PublicFaceScanEncryptionKey =
    "-----BEGIN PUBLIC KEY-----\n" +
      "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3N+du5DlZCuJQkLlj4Hk\n" +
      "xXKsnGa/weUO5juAzBVg3NpQ1i/2b+w0LeQviudSeFhgaId5JD327BHgqgsrNNVH\n" +
      "x6MtmlEMNvpfWFmuFUUcySVx4WU1QqeI20hxaCLCc6Kwcq5Z1ntaDQkyU8/e83VX\n" +
      "On1zofh1iD2pNdNUgbFrwABs+x+rpNXhWRcqTgJmPE40U0pLoBrajIUtsOO2vLpi\n" +
      "RetJuNbYMUjJmlnjnYjk435J9yDl0nmKWAB7u4BBbAUUiAkcKqEHuPUUpPkLI6NZ\n" +
      "yBuXCHCvxUOtVxCoOD/ITqN7ftjmSOI4NAYDRZtgWHuH8JshbgzOm9atIQhW+3qO\n" +
      "0wIDAQAB\n" +
      "-----END PUBLIC KEY-----";
    ;

  public static String ProductionKeyText =
    "appId      = \"com.numio.pay,com.facetec.sampleapp,com.example.reactnativefacetec,com.numio.app\"\n" +
      "expiryDate = 2021-08-10\n" +
      "key        = 003045022100de632f36a0086ae341ad1b88213c22c41c713b1147efb6a98541b4dbec2d806a0220448e404346d7d790886ff172b17b936c816ba6bce8a6bdd08d8acf4c6cec49cf\n";

  // -------------------------------------
  // Convenience method to initialize the FaceTec SDK.
  // NOTE: This function is auto-populated by the FaceTec SDK Configuration Wizard based on the Keys issued to your Apps.
  public static void initializeFaceTecSDKFromAutogeneratedConfig(Context context, FaceTecSDK.InitializeCallback callback) {
    FaceTecSDK.initializeInDevelopmentMode(context, DeviceKeyIdentifier, PublicFaceScanEncryptionKey, callback);
  }

  // -------------------------------------
  // This app can modify the customization to demonstrate different look/feel preferences
  // NOTE: This function is auto-populated by the FaceTec SDK Configuration Wizard based on your UI Customizations you picked in the Configuration Wizard GUI.
  public static FaceTecCustomization retrieveConfigurationWizardCustomization() {
    return new FaceTecCustomization();
  }

  public static FaceTecCustomization currentCustomization = retrieveConfigurationWizardCustomization();

  // -------------------------------------
  // Boolean to indicate the FaceTec SDK Configuration Wizard was used to generate this file.
  // In this Sample App, if this variable is true, a "Config Wizard Theme" will be added to this App's Design Showcase,
  // and choosing this option will set the FaceTec SDK UI/UX Customizations to the Customizations that you selected in the
  // Configuration Wizard.
  public static boolean wasSDKConfiguredWithConfigWizard = false;
}
